apiVersion: v1
kind: Service
metadata:
  name: vote
  labels:
    name: voting-service
    app: demo-voting-app
spec:
  type: NodePort
  selector:
    name: voting-app-pod
    app: demo-voting-app
  ports:
    - port: 8080
      targetPort: 80
      nodePort: 31000
